# Generated by Django 2.1.4 on 2018-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jedi',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='jedi',
            name='last_name',
            field=models.CharField(default='sdf', max_length=255),
            preserve_default=False,
        ),
    ]
