# Generated by Django 2.1.4 on 2018-12-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20181218_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='jedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jedi_candidates', to='academy.Jedi'),
        ),
    ]
