# Generated by Django 2.1.4 on 2018-12-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20181219_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
