# Generated by Django 2.1.4 on 2018-12-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20181219_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='academy.Planet'),
        ),
    ]
